import 'package:flutter/material.dart';

class WidgetKey {
  static Key BT_BACK_PAGE = Key('BT_BACK_PAGE');
  
  static Key LOGIN_TF_USERNAME = Key('LOGIN_TF_USERNAME');
  static Key LOGIN_TF_PASSWORD = Key('LOGIN_TF_PASSWORD');
  static Key LOGIN_BT_LOGIN = Key('LOGIN_BT_LOGIN');

  static Key HOME_ICONMENU_VEHICLE = Key('HOME_ICONMENU_VEHICLE');
  static Key HOME_ICONMENU_FAVORITE = Key('HOME_ICONMENU_FAVORITE');
  static Key HOME_ICONMENU_PAYMENT = Key('HOME_ICONMENU_PAYMENT');
  static Key HOME_ICONMENU_COUPON = Key('HOME_ICONMENU_COUPON');
  static Key HOME_ICONMENU_FLEETCARD = Key('HOME_ICONMENU_FLEETCARD');
  static Key HOME_ICONMENU_FLEETOPERATION = Key('HOME_ICONMENU_FLEETOPERATION');
}
